### ISSUE TITLE
Nonce duplication occurs when executing subsequent transactions

### ISSUE THREAD

**Issue by danijelTxFusion** [matter-labs/local-setup#12]
🐛 Bug Report for zkSync Era local-node

📝 Description

We are running tests against local-node and frequently encounter an error with `ethers v6`. The error message received states: `Nonce has already been used`. This error exhibits non-deterministic behavior, as the test only passes sporadically—one in every ten attempts. Initially, we suspected that the wait() function from `ethers v6` might not reliably await the transaction receipt. However, testing confirmed it does wait until the transaction is processed before proceeding with the test execution. The problem arises when preparing the next transaction; the server appears to return the nonce from the previous transaction. It seems the server does not update the nonce quickly enough in the brief interval between transactions. When we introduced a small timeout before populating the transaction and giving the time for the node to increment the nonce, it worked.

🔄 Reproduction Steps

Test fails:
```shell
git clone https://github.com/zksync-sdk/zksync-ethers.git
cd zksync-ethers
git checkout 3daf4a0fe88777936485d24342f665d77302f902

yarn install
yarn mocha -r ts-node/register tests/integration/paymaster.test.ts
```
Output:
```
Error: nonce has already been used (transaction="0x71f923f514840ee6b280840ee6b2808303235094000000000000000000000000000000000000800680b8c4ecf95b8a0000000000000000000000000000000000000000000000000000000000000000010001155cf2210935293fd243f56453d4134416ebed356c0c43f823871475fe000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000d4567aa4fd1b32a16c16cbff9d9a69e51cf7229382010e808082010e9436615cf349d7f6344891b1e7ca7c72883f5dc04982c350f922a3b922a00004000000000002000700000000000200000000030100190000006003300270000000ed0430019700030000004103550002000000010355000000ed0030019d000100000000001f0000000101200190000000340000c13d0000008001000039000000400010043f0000000002000031000000040120008c000000430000413d0000000201000367000000000301043b000000e003300270000000f30430009c0000007c0000613d000000f40430009c000000d40000613d000000f50130009c000000fc0000c13d0000000001000416000000000110004c000000fc0000c13d000000040100008a0000000001100031000000ef02000041000000000310004c00000000030000190000000003024019000000ef01100197000000000410004c000000000200a019000000ef0110009c00000000010300190000000001026019000000000110004c000000fc0000c13d000000000100041a000000f001100197000000400200043d0000000000120435000000ed01000041000000ed0320009c00000000010240190000004001100210000000f6011001c7000003ae0001042e0000000001000416000000000110004c000000fc0000c13d00000000010000310000009f02100039000000200300008a000000000232016f000000ee0320009c000000470000413d000001040100004100000000001004350000004101000039000000040010043f0000010501000041000003af00010430000000000120004c000000fc0000c13d0000000001000019000003ae0001042e000000400020043f0000001f0210018f00000002030003670000000504100272000000550000613d00000000050000190000000506500210000000000763034f000000000707043b000000800660003900000000007604350000000105500039000000000645004b0000004d0000413d000000000520004c000000640000613d0000000504400210000000000343034f00000003022002100000008004400039000000000504043300000000052501cf000000000525022f000000000303043b0000010002200089000000000323022f00000000022301cf000000000252019f0000000000240435000000ef02000041000000200310008c00000000030000190000000003024019000000ef01100197000000000410004c000000000200a019000000ef0110009c00000000010300190000000001026019000000000110004c000000fc0000c13d000000800100043d000000f00210009c000000fc0000213d000000000200041a000000f102200197000000000112019f000000000010041b000000200100003900000100001004430000012000000443000000f201000041000003ae0001042e000000040320008a000000ef04000041000000600530008c00000000050000190000000005044019000000ef03300197000000000630004c000000000400a019000000ef0330009c00000000030500190000000003046019000000000330004c000000fc0000c13d0000004403100370000000000a03043b000000f703a0009c000000fc0000213d0000000403a000390000000004320049000000ef05000041000002600640008c00000000060000190000000006054019000000ef04400197000000000740004c000000000500a019000000ef0440009c00000000040600190000000004056019000000000440004c000000fc0000c13d0000000004000411000080010440008c000000fe0000c13d0000022404a00039000000000441034f0000000005a20049000000230550008a000000000404043b000000ef06000041000000000754004b00000000070000190000000007068019000000ef05500197000000ef08400197000000000958004b0000000006008019000000000558013f000000ef0550009c00000000050700190000000005066019000000000550004c000000fc0000c13d0000000003340019000000000431034f000000000404043b000000f70540009c000000fc0000213d00000000054200490000002002300039000000ef06000041000000000752004b00000000070000190000000007062019000000ef05500197000000ef08200197000000000958004b0000000006008019000000000558013f000000ef0550009c00000000050700190000000005066019000000000550004c000000fc0000c13d000000030540008c000001220000213d000000f801000041000000800010043f0000002001000039000000840010043f0000003a01000039000000a40010043f0000010a01000041000000c40010043f0000010b01000041000000e40010043f000000fb01000041000003af00010430000000040320008a000000ef04000041000000c00530008c00000000050000190000000005044019000000ef06300197000000000760004c000000000400a019000000ef0660009c000000000405c019000000000440004c000000fc0000c13d0000000404100370000000000404043b000000f70540009c000000fc0000213d0000002305400039000000ef06000041000000000725004b00000000070000190000000007068019000000ef08200197000000ef05500197000000000985004b0000000006008019000000000585013f000000ef0550009c00000000050700190000000005066019000000000550004c000000fc0000c13d0000000405400039000000000551034f000000000505043b000000f70650009c000000fc0000213d00000000045400190000002404400039000000000224004b0000010a0000a13d0000000001000019000003af00010430000000f801000041000000800010043f0000002001000039000000840010043f0000002401000039000000a40010043f000000f901000041000000c40010043f000000fa01000041000000e40010043f000000fb01000041000003af000104300000002402100370000000000202043b000000f70420009c000000fc0000213d0000000002230049000000ef03000041000002600420008c00000000040000190000000004034019000000ef02200197000000000520004c000000000300a019000000ef0220009c00000000020400190000000002036019000000000220004c000000fc0000c13d0000008401100370000000000101043b000000010110008c000000fc0000213d03ad038a0000040f0000000001000019000003ae0001042e000000000221034f000000000202043b000000fc02200197000000fd0220009c000001970000c13d000000040240008a000000600420008c000000fc0000413d0000002404300039000000000541034f000000000505043b000700000005001d000000f00550009c000000fc0000213d0000006405300039000000000551034f0000004403300039000000000331034f000000000303043b000600000003001d000000000305043b000000f70530009c000000fc0000213d000000000242001900000000034300190000001f04300039000000ef05000041000000000624004b00000000060000190000000006058019000000ef04400197000000ef07200197000000000874004b0000000005008019000000000474013f000000ef0440009c00000000040600190000000004056019000000000440004c000000fc0000c13d00050000000a001d000000000131034f000000000101043b000000f70410009c0000003d0000213d000000bf04100039000000200500008a000000000454016f000000f70540009c0000003d0000213d000000400040043f000000800010043f00000020033000390000000004310019000000000224004b000000fc0000213d0000001f0210018f00000002033003670000000504100272000001670000613d00000000050000190000000506500210000000000763034f000000000707043b000000a00660003900000000007604350000000105500039000000000645004b0000015f0000413d000000000520004c000001760000613d0000000504400210000000000343034f0000000302200210000000a004400039000000000504043300000000052501cf000000000525022f000000000303043b0000010002200089000000000323022f00000000022301cf000000000252019f0000000000240435000000a0011000390000000000010435000000000100041a000000f0011001970000000702000029000000000112004b000001a10000c13d000000050100002900000024011000390000000201100367000000000101043b000000400400043d000001020200004100000000002404350000000002000410000000f0032001970000002402400039000100000003001d0000000000320435000000f002100197000400000004001d0000000401400039000200000002001d000000000021043500000000010004140000000702000029000000040220008c000001b30000c13d0000000103000031000000200130008c00000020040000390000000004034019000001e60000013d000000f801000041000000800010043f0000002001000039000000840010043f0000001a01000039000000a40010043f000000fe01000041000000c40010043f000000ff01000041000003af00010430000000400100043d00000044021000390000010003000041000000000032043500000024021000390000000d030000390000000000320435000000f8020000410000000000210435000000040210003900000020030000390000000000320435000000ed02000041000000ed0310009c0000000001028019000000400110021000000101011001c7000003af00010430000000ed02000041000000ed0310009c00000000010280190000000404000029000000ed0340009c00000000020440190000004002200210000000c001100210000000000121019f00000103011001c7000000070200002903ad03a80000040f000000040a00002900000000030100190000006003300270000000ed03300197000000200430008c000000200400003900000000040340190000001f0540018f0000000506400272000001d20000613d0000000007000019000000050870021000000000098a0019000000000881034f000000000808043b00000000008904350000000107700039000000000867004b000001ca0000413d000000000750004c000001e20000613d0000000506600210000000000761034f000000040800002900000000066800190000000305500210000000000806043300000000085801cf000000000858022f000000000707043b0000010005500089000000000757022f00000000055701cf000000000585019f0000000000560435000100000003001f000300000001035500000001022001900000020c0000613d0000001f01400039000000600110018f00000004020000290000000002210019000000000112004b00000000010000190000000101004039000300000002001d000000f70220009c0000003d0000213d00000001011001900000003d0000c13d0000000301000029000000400010043f000000200130008c000000fc0000413d00000004010000290000000001010433000000000110004c000002320000c13d0000000303000029000000440130003900000109020000410000000000210435000000240130003900000015020000390000000000210435000000f8010000410000000000130435000000040130003900000020020000390000000000210435000000ed01000041000000ed0230009c0000000001034019000000400110021000000101011001c7000003af00010430000000400200043d0000001f0430018f0000000503300272000002190000613d000000000500001900000005065002100000000007620019000000000661034f000000000606043b00000000006704350000000105500039000000000635004b000002110000413d000000000540004c000002280000613d0000000503300210000000000131034f00000000033200190000000304400210000000000503043300000000054501cf000000000545022f000000000101043b0000010004400089000000000141022f00000000014101cf000000000151019f0000000000130435000000ed010000410000000103000031000000ed0430009c0000000003018019000000ed0420009c000000000102401900000040011002100000006002300210000000000112019f000003af00010430000000050400002900000064014000390000000202000367000000000312034f000000a401400039000000000112034f000000000101043b000000000203043b00000000341200a9000500000004001d000000000320004c000002420000613d000000050300002900000000322300d9000000000112004b000002c10000c13d00000003030000290000004401300039000000060200002900000000002104350000002401300039000000010200002900000000002104350000010601000041000000000013043500000004013000390000000202000029000000000021043500000000010004140000000702000029000000040220008c000002570000c13d0000000103000031000000200130008c000000200400003900000000040340190000028a0000013d000000ed02000041000000ed0310009c00000000010280190000000304000029000000ed0340009c00000000020440190000004002200210000000c001100210000000000121019f00000101011001c7000000070200002903ad03a30000040f000000030a00002900000000030100190000006003300270000000ed03300197000000200430008c000000200400003900000000040340190000001f0540018f0000000506400272000002760000613d0000000007000019000000050870021000000000098a0019000000000881034f000000000808043b00000000008904350000000107700039000000000867004b0000026e0000413d000000000750004c000002860000613d0000000506600210000000000761034f000000030800002900000000066800190000000305500210000000000806043300000000085801cf000000000858022f000000000707043b0000010005500089000000000757022f00000000055701cf000000000585019f0000000000560435000100000003001f00030000000103550000000101200190000002c70000613d0000001f01400039000000600110018f00000003020000290000000001210019000000f70210009c0000003d0000213d000000400010043f000000200130008c000000fc0000413d00000003010000290000000001010433000000000210004c0000000002000019000000010200c039000000000121004b000000fc0000c13d000000ed03000041000700000003001d0000000001000414000000ed0210009c0000000001038019000000c00110021000000108021001c70000000503000029000000000430004c000000000102c019000080090200003900008001020060390000800104000039000000000500001903ad03a30000040f000600000002001d00000000020100190000006002200270000100ed0020019d000300000001035503ad032b0000040f0000000601000029000000010110018f03ad036f0000040f000000400100043d000600000001001d03ad03110000040f00000006040000290000000001410049000000ed0210009c00000007030000290000000001038019000000ed0240009c0000000002030019000000000204401900000040022002100000006001100210000000000121019f000003ae0001042e000001040100004100000000001004350000001101000039000000040010043f0000010501000041000003af000104300000006001000039000000000230004c000002f40000613d0000003f013000390000010702100197000000400100043d0000000002210019000000000412004b00000000040000190000000104004039000000f70520009c0000003d0000213d00000001044001900000003d0000c13d000000400020043f0000000002310436000000030300036700000001050000310000001f0450018f0000000505500272000002e50000613d000000000600001900000005076002100000000008720019000000000773034f000000000707043b00000000007804350000000106600039000000000756004b000002dd0000413d000000000640004c000002f40000613d0000000505500210000000000353034f00000000025200190000000304400210000000000502043300000000054501cf000000000545022f000000000303043b0000010004400089000000000343022f00000000034301cf000000000353019f00000000003204350000000021010434000000050310008c000003000000413d000000ed03000041000000ed0420009c0000000002038019000000ed0410009c000000000103801900000060011002100000004002200210000000000121019f000003af00010430000000400200043d000700000002001d000000f8010000410000000000120435000000040120003903ad03620000040f00000007040000290000000001410049000000ed02000041000000ed0310009c0000000001028019000000ed0340009c000000000204401900000040022002100000006001100210000000000121019f000003af000104300000002002100039000000400300003900000000003204350000010c0200004100000000002104350000004003100039000000600200043d00000000002304350000006001100039000000000320004c000003240000613d000000000300001900000000043100190000008005300039000000000505043300000000005404350000002003300039000000000423004b0000031d0000413d000000000321001900000000000304350000001f02200039000000200300008a000000000232016f0000000001210019000000000001042d000000600100003900000001020000320000035b0000613d000000ee0120009c0000035c0000813d0000003f01200039000000200300008a000000000331016f000000400100043d0000000003310019000000000413004b00000000040000190000000104004039000000f70530009c0000035c0000213d00000001044001900000035c0000c13d000000400030043f0000000002210436000000030300036700000001050000310000001f0450018f00000005055002720000034c0000613d000000000600001900000005076002100000000008720019000000000773034f000000000707043b00000000007804350000000106600039000000000756004b000003440000413d000000000640004c0000035b0000613d0000000505500210000000000353034f00000000025200190000000304400210000000000502043300000000054501cf000000000545022f000000000303043b0000010004400089000000000343022f00000000034301cf000000000353019f0000000000320435000000000001042d000001040100004100000000001004350000004101000039000000040010043f0000010501000041000003af0001043000000060021000390000010d03000041000000000032043500000040021000390000010e03000041000000000032043500000020021000390000002a030000390000000000320435000000200200003900000000002104350000008001100039000000000001042d000000000110004c000003720000613d000000000001042d000000400100043d00000084021000390000010f030000410000000000320435000000640210003900000110030000410000000000320435000000440210003900000111030000410000000000320435000000240210003900000053030000390000000000320435000000f8020000410000000000210435000000040210003900000020030000390000000000320435000000ed02000041000000ed0310009c0000000001028019000000400110021000000112011001c7000003af000104300000000001000411000080010110008c0000038e0000c13d000000000001042d000000400100043d0000006402100039000000fa0300004100000000003204350000004402100039000000f9030000410000000000320435000000240210003900000024030000390000000000320435000000f8020000410000000000210435000000040210003900000020030000390000000000320435000000ed02000041000000ed0310009c0000000001028019000000400110021000000113011001c7000003af00010430000003a6002104210000000102000039000000000001042d0000000002000019000000000001042d000003ab002104230000000102000039000000000001042d0000000002000019000000000001042d000003ad00000432000003ae0001042e000003af00010430000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff00000000000000000000000000000000000000000000000100000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0000000000000000000000000000000000000000000000020000000000000000000000000000004000000100000000000000000000000000000000000000000000000000000000000000000000000000038a24bc00000000000000000000000000000000000000000000000000000000817b17f00000000000000000000000000000000000000000000000000000000085fa292f0000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000ffffffffffffffff08c379a0000000000000000000000000000000000000000000000000000000004f6e6c7920626f6f746c6f616465722063616e2063616c6c2074686973206d6574686f64000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000084000000800000000000000000ffffffff00000000000000000000000000000000000000000000000000000000949431dc00000000000000000000000000000000000000000000000000000000556e737570706f72746564207061796d617374657220666c6f770000000000000000000000000000000000000000000000000064000000800000000000000000496e76616c696420746f6b656e000000000000000000000000000000000000000000000000000000000000000000000000000064000000000000000000000000dd62ed3e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000440000000000000000000000004e487b7100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002400000000000000000000000023b872dd0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001ffffffe002000000000000000000000000000000000000000000000000000000000000004d696e20616c6c6f77616e636520746f6f206c6f770000000000000000000000546865207374616e64617264207061796d617374657220696e707574206d757374206265206174206c656173742034206279746573206c6f6e67000000000000038a24bc000000000000000000000000000000000000000000000000000000007327206163636f756e74000000000000000000000000000000000000000000004661696c656420746f207472616e7366657246726f6d2066726f6d207573657269676874206e6f7420626520656e6f7567682e0000000000000000000000000020626f6f746c6f616465722e205061796d61737465722062616c616e6365206d4661696c656420746f207472616e736665722074782066656520746f2074686500000000000000000000000000000000000000a40000000000000000000000000000000000000000000000000000000000000084000000000000000000000000434a265b4e19f3e86ad50cc06218d532431413c7e6ec41818ab568730a6a8c79b8415f8403af53c5a92fd68a7aa1211aecef4ac0d8e1c4ff2354ac835402159af9783d46fb84eaeaf188a149d256409b3ed2eb65a4ef97ed8c66b61fe34477fca5ed1bc0", info={ "error": { "code": 3, "data": "0x", "message": "nonce too low. allowed nonce range: 21 - 71, actual: 20" } }, code=NONCE_EXPIRED, version=6.9.0)
      at makeError (node_modules/ethers/src.ts/utils/errors.ts:694:21)
      at Provider.getRpcError (node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:979:33)
      at /home/danijel/projects/matterlabs/sdk/zksync-ethers/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:527:45
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

Test passes when wait is added between transactions:
```shell
git clone https://github.com/zksync-sdk/zksync-ethers.git
cd zksync-ethers
git checkout d1dcafd4338a04024c401ce88cc97e9d629c3e29

yarn install
yarn mocha -r ts-node/register tests/integration/paymaster.test.ts
```

Output:
```
  Paymaster
    #ApprovalBased
      ✔ use ERC20 token to pay transaction fee (10447ms)


  1 passing (10s)
```

What is changed in contract:
```typescript
await tokenContract.mint(
    Typed.address(await wallet.getAddress()),
    Typed.uint256(INIT_MINT_AMOUNT),
);

await utils.sleep(1000); // workaround for duplicated nonce
.....
const paymasterContract = await accountFactory.deploy(tokenAddress);
```

🤔 Expected Behavior

Transactions are processed sequentially without errors, with local-node correctly incrementing the nonce for each new transaction.

😯 Current Behavior

Test only passes sporadically—one in every ten attempts

🖥️ Environment

    Rust version: rustc 1.70.0
    Operating System & Version: macOS, 13.3.1, apple chip M2, Linux

📋 Additional Context

Tests with `ethers v5` were successful. The `ethers v5` and `ethers v6` implementations differ, with the v6 code being more optimized. In the v5 versions there were a lot of (redundant) steps that, in our opinion, give enough time for era-test-node to increment the nonce for the account.

**Comment by danijelTxFusion** [comment]
False positive. This issue is not related to node but to the `ethers v6` implementation when interacting with contracts.

In ethers v5, it would wait for the transaction to be confirmed: 
```
await tokenContract.mint(
    Typed.address(await wallet.getAddress()),
    Typed.uint256(INIT_MINT_AMOUNT),
);
```

In ethers v6, waiting for the transaction needs to be explicitly specified:
```
const mintTx = await tokenContract.mint(
    Typed.address(await wallet.getAddress()),
    Typed.uint256(INIT_MINT_AMOUNT),
) as ethers.ContractTransactionResponse;
await mintTx.wait();
```
