### ISSUE TITLE
Local setup fails after latest changes

### ISSUE THREAD

**Issue by pcaversaccio** [matter-labs/local-setup#17]
I just tried your latest version (commit https://github.com/matter-labs/local-setup/commit/2605e172467f014121df51fed6006df25921c96a) and I face the following issue when I run `./start.sh`:

![image](https://github.com/matter-labs/local-setup/assets/25297591/378e66f8-2d2e-4151-b517-926230a6512e)

Previous versions worked well for me.

Furthermore, I face on my machine many times the following issue:

```
Error response from daemon: Ports are not available: exposing port TCP 127.0.0.1:5432 -> 0.0.0.0:0: listen tcp 127.0.0.1:5432: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```

I changed the ports manually which fixes it, but maybe can we change the default ones as well to something different than `5432`?

**Comment by MexicanAce** [comment]
Port `5432` is the default port for PostgreSQL and we should maintain the default ports for external services. 

It's strange if your machine already uses that port, that would imply there's another instance of Postgres running locally that could conflict with this instance.

**Comment by pcaversaccio** [comment]
> Port `5432` is the default port for PostgreSQL and we should maintain the default ports for external services.
> 
> It's strange if your machine already uses that port, that would imply there's another instance of Postgres running locally that could conflict with this instance.
> 
> Important to note that this port has not been changed with any recent changes.

Thanks I uninstalled my PostgreSQL accordingly, and this fixed the port issue. But the bigger issue I have is that Docker fails with the following error:

```console
$ node build/index.js f yarn --cwd /infrastructure/local-setup-preparation start
$ ts-node ./src/index.ts
                    zksync-1    | /infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:859
                    zksync-1    |     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
                    zksync-1    |            ^
                    zksync-1    | TSError: ⨯ Unable to compile TypeScript:
                    zksync-1    | src/index.ts:14:10 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
                    zksync-1    | 
                    zksync-1    | 14     if (!process.env.CONTRACTS_DIAMOND_PROXY_ADDR) {
                    zksync-1    |             ~~~~~~~
                    zksync-1    | src/index.ts:22:42 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
                    zksync-1    | 
                    zksync-1    | 22     const contract = new ethers.Contract(process.env.CONTRACTS_DIAMOND_PROXY_ADDR, utils.ZKSYNC_MAIN_ABI, ethProvider);
                    zksync-1    |                                             ~~~~~~~
                    zksync-1    | src/index.ts:31:46 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
                    zksync-1    | 
                    zksync-1    | 31         const contract = new ethers.Contract(process.env.CONTRACTS_DIAMOND_PROXY_ADDR, utils.ZKSYNC_MAIN_ABI, wallet);
                    zksync-1    |                                                 ~~~~~~~
                    zksync-1    | 
                    zksync-1    |     at createTSError (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:859:12)
                    zksync-1    |     at reportTSError (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:863:19)
                    zksync-1    |     at getOutput (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:1077:36)
                    zksync-1    |     at Object.compile (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:1433:41)
                    zksync-1    |     at Module.m._compile (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:1617:30)
                    zksync-1    |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
                    zksync-1    |     at Object.require.extensions.<computed> [as .ts] (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:1621:12)
                    zksync-1    |     at Module.load (node:internal/modules/cjs/loader:1119:32)
                    zksync-1    |     at Function.Module._load (node:internal/modules/cjs/loader:960:12)
                    zksync-1    |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
                    zksync-1    |   diagnosticCodes: [ 2580, 2580, 2580 ]
                    zksync-1    | }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
zksync-1 exited with code 1
```

**Comment by arose00** [comment]
Hey @pcaversaccio - I noticed your comment but also that the issue was closed, so this may have been missed. 

Did this get resolved? Otherwise we should re-open (or move this to a new issue for better ticket hygiene)

**Comment by pcaversaccio** [comment]
> Hey @pcaversaccio - I noticed your comment but also that the issue was closed, so this may have been missed. 
> 
> Did this get resolved? Otherwise we should re-open (or move this to a new issue for better ticket hygiene) 

I already created a follow-up issue, which finally got (almost; patch PR merge pending) resolved: https://github.com/matter-labs/local-setup/issues/20.
