### ISSUE TITLE
Docker fails with ` TSError: ⨯ Unable to compile TypeScript:`

### ISSUE THREAD

**Issue by pcaversaccio** [matter-labs/local-setup#20]
I just tried your latest version (commit https://github.com/matter-labs/local-setup/commit/2605e172467f014121df51fed6006df25921c96a) and I face the following issue when I run ./start.sh:

```console
$ node build/index.js f yarn --cwd /infrastructure/local-setup-preparation start
$ ts-node ./src/index.ts
                    zksync-1    | /infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:859
                    zksync-1    |     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
                    zksync-1    |            ^
                    zksync-1    | TSError: ⨯ Unable to compile TypeScript:
                    zksync-1    | src/index.ts:14:10 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
                    zksync-1    | 
                    zksync-1    | 14     if (!process.env.CONTRACTS_DIAMOND_PROXY_ADDR) {
                    zksync-1    |             ~~~~~~~
                    zksync-1    | src/index.ts:22:42 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
                    zksync-1    | 
                    zksync-1    | 22     const contract = new ethers.Contract(process.env.CONTRACTS_DIAMOND_PROXY_ADDR, utils.ZKSYNC_MAIN_ABI, ethProvider);
                    zksync-1    |                                             ~~~~~~~
                    zksync-1    | src/index.ts:31:46 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
                    zksync-1    | 
                    zksync-1    | 31         const contract = new ethers.Contract(process.env.CONTRACTS_DIAMOND_PROXY_ADDR, utils.ZKSYNC_MAIN_ABI, wallet);
                    zksync-1    |                                                 ~~~~~~~
                    zksync-1    | 
                    zksync-1    |     at createTSError (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:859:12)
                    zksync-1    |     at reportTSError (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:863:19)
                    zksync-1    |     at getOutput (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:1077:36)
                    zksync-1    |     at Object.compile (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:1433:41)
                    zksync-1    |     at Module.m._compile (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:1617:30)
                    zksync-1    |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
                    zksync-1    |     at Object.require.extensions.<computed> [as .ts] (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:1621:12)
                    zksync-1    |     at Module.load (node:internal/modules/cjs/loader:1119:32)
                    zksync-1    |     at Function.Module._load (node:internal/modules/cjs/loader:960:12)
                    zksync-1    |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
                    zksync-1    |   diagnosticCodes: [ 2580, 2580, 2580 ]
                    zksync-1    | }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
zksync-1 exited with code 1
```

**Comment by benceharomi** [comment]
Do you use the [latest local-node docker image](https://hub.docker.com/layers/matterlabs/local-node/latest2.0/images/sha256-7caf61fac152986915ff8d865a136f78b695a5ed3587883218fb2fd37fe67140?context=explore)?

Please make sure that the used images are the following:
* [matterlabs/local-node:latest2.0](https://hub.docker.com/layers/matterlabs/local-node/latest2.0/images/sha256-7caf61fac152986915ff8d865a136f78b695a5ed3587883218fb2fd37fe67140)
* [postgres:14](https://hub.docker.com/layers/library/postgres/14/images/sha256-a28005f051c26406f8e718e411a1068462a297dae049cddb513194d36dd8f29f)
* [reth:v0.2.0-beta.2](https://github.com/paradigmxyz/reth/pkgs/container/reth/190594989?tag=v0.2.0-beta.2)
```
➜  ~ docker inspect --format='{{index .RepoDigests 0}}' matterlabs/local-node:latest2.0

matterlabs/local-node@sha256:7caf61fac152986915ff8d865a136f78b695a5ed3587883218fb2fd37fe67140
➜  ~ docker inspect --format='{{index .RepoDigests 0}}' postgres:14

postgres@sha256:d6850c40261fdc9a4fb33b9521d9d641c4a5dcb82145f7bcc32c9258f81e75a2
➜  ~ docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/paradigmxyz/reth:v0.2.0-beta.2

ghcr.io/paradigmxyz/reth@sha256:ce7f45d7fd54245b51d8b17935da801d87978d8eabec1d3cda6abf0d133373f8
```

**Comment by pcaversaccio** [comment]
> This [PR](https://github.com/matter-labs/zksync-era/pull/1808) will fix the rich-wallet issue, we will generate a new docker image for local-node once it's merged.

Great - will wait for the merge and your update. Since the original issue got resolved, closing the issue. Thx!

**Comment by benceharomi** [comment]
@pcaversaccio rich accounts are rich again: https://github.com/matter-labs/local-setup/issues/19#issuecomment-2100343787
